"use client";
// The department / office mark set.
//
// GENERATED — regenerate rather than hand-edit (see the picker mockup script).
//
// Icons are lucide, the same library the rest of Quorly draws with, so a department's
// mark and the app's own chrome come from one hand. They are stroke SVG with no fill,
// which is why they take the colour of whatever surface they sit on — indigo in the
// rail, white when the row is selected. An emoji cannot do that: it is a coloured
// picture, not a mark.
//
// Stored in ONE column: an icon as "lucide:<name>", an emoji as the character itself.
// Nothing had to migrate — the emoji already chosen keep working untouched.
import type { LucideIcon } from "lucide-react";
import { Activity, Ambulance, Archive, AtSign, Award, Banknote, Bell, Bike, Book, BookOpen, Bookmark, BookmarkCheck, Brain, BrickWall, Briefcase, Brush, Building, Building2, Bus, Cake, Calculator, Calendar, CalendarCheck, CalendarDays, Camera, Car, CarFront, Caravan, ChartColumn, CheckCheck, ChefHat, CircleDot, CircleParking, CircleX, ClipboardList, Clock, CloudSun, Coffee, Cog, Coins, Compass, Construction, CreditCard, Croissant, Cross, Crown, CupSoda, Dices, Drama, Drill, Dumbbell, Earth, Feather, FileStack, Film, FireExtinguisher, Fish, Flag, FlaskConical, Flower, Folders, Footprints, Forklift, Fuel, Gavel, Globe, GraduationCap, Group, Hammer, Hand, HandCoins, HandHeart, Handshake, HardHat, Hash, Heart, HeartHandshake, Hourglass, House, Inbox, Infinity, KeyRound, Landmark, Laptop, Leaf, LifeBuoy, Lightbulb, Lock, Mail, Map, MapPin, Medal, Megaphone, MessagesSquare, Mic, Microscope, Milestone, Monitor, MountainSnow, Music, Navigation, Newspaper, Package, PaintRoller, Palette, Paperclip, PartyPopper, PawPrint, PenTool, Pencil, Phone, PiggyBank, Pill, Pin, Plug, Presentation, Radio, Receipt, Repeat, Route, Rss, Ruler, Scale, School, Scroll, Send, Shapes, Shield, ShoppingCart, Signature, Siren, Smartphone, Snowflake, Soup, Sparkles, Sprout, Square, Stamp, Star, Stethoscope, Sun, Tag, Target, Telescope, Tent, TentTree, Ticket, TrafficCone, Trees, TrendingDown, TrendingUp, Triangle, Trophy, Truck, UserCheck, UserPlus, Users, Utensils, Vault, Video, Volleyball, Vote, Wallet, WavesLadder, Wheat, Wrench, Zap } from "lucide-react";

export const ICON_GROUPS: { en: string; fr: string; names: string[] }[] = [
  { en: "Governance & records", fr: "Gouvernance & registres", names: ["landmark", "gavel", "scale", "vote", "scroll", "feather", "pen-tool", "clipboard-list", "folders", "archive", "file-stack", "tag", "bookmark", "pin", "paperclip", "ruler", "key-round", "shield", "crown", "award", "stamp", "signature"] },
  { en: "Money & treasury", fr: "Argent & tr\u00e9sorerie", names: ["banknote", "coins", "credit-card", "receipt", "piggy-bank", "wallet", "calculator", "chart-column", "trending-up", "trending-down", "lock", "vault", "hand-coins"] },
  { en: "Meetings & time", fr: "R\u00e9unions & temps", names: ["calendar", "calendar-days", "calendar-check", "clock", "hourglass", "bell", "megaphone", "mic", "messages-square", "handshake", "check-check", "circle-x", "repeat", "video", "presentation"] },
  { en: "Communication", fr: "Communication", names: ["mail", "inbox", "send", "phone", "smartphone", "radio", "newspaper", "monitor", "laptop", "globe", "rss", "at-sign"] },
  { en: "Work & trades", fr: "Travail & m\u00e9tiers", names: ["wrench", "hammer", "cog", "briefcase", "drill", "brick-wall", "construction", "hard-hat", "fire-extinguisher", "plug", "paint-roller", "package", "brush"] },
  { en: "Transport & road", fr: "Transport & route", names: ["truck", "bus", "car", "car-front", "caravan", "fuel", "map", "map-pin", "compass", "traffic-cone", "siren", "route", "navigation", "circle-parking", "milestone", "forklift"] },
  { en: "Learning & study", fr: "Formation & \u00e9tude", names: ["book", "book-open", "graduation-cap", "school", "microscope", "telescope", "flask-conical", "lightbulb", "brain", "pencil", "medal"] },
  { en: "Care & wellbeing", fr: "Sant\u00e9 & entraide", names: ["stethoscope", "cross", "pill", "ambulance", "heart-handshake", "heart", "life-buoy", "hand-heart", "activity"] },
  { en: "Community & people", fr: "Communaut\u00e9 & personnes", names: ["users", "user-plus", "user-check", "hand", "house", "building", "building-2", "earth", "tent-tree", "group"] },
  { en: "Food & hospitality", fr: "Alimentation & accueil", names: ["utensils", "coffee", "croissant", "soup", "chef-hat", "shopping-cart", "cake", "cup-soda", "wheat"] },
  { en: "Culture & celebration", fr: "Culture & f\u00eates", names: ["party-popper", "drama", "music", "palette", "film", "camera", "trophy", "ticket", "sparkles"] },
  { en: "Sport & recreation", fr: "Sport & loisirs", names: ["volleyball", "dumbbell", "bike", "footprints", "fish", "tent", "dices", "target", "waves-ladder"] },
  { en: "Nature & seasons", fr: "Nature & saisons", names: ["leaf", "trees", "snowflake", "sun", "sprout", "paw-print", "cloud-sun", "flower", "mountain-snow"] },
  { en: "Marks & symbols", fr: "Marques & symboles", names: ["star", "square", "triangle", "flag", "hash", "infinity", "zap", "bookmark-check", "shapes", "circle-dot"] },
];

export const ICONS: Record<string, LucideIcon> = {
  "landmark": Landmark,
  "gavel": Gavel,
  "scale": Scale,
  "vote": Vote,
  "scroll": Scroll,
  "feather": Feather,
  "pen-tool": PenTool,
  "clipboard-list": ClipboardList,
  "folders": Folders,
  "archive": Archive,
  "file-stack": FileStack,
  "tag": Tag,
  "bookmark": Bookmark,
  "pin": Pin,
  "paperclip": Paperclip,
  "ruler": Ruler,
  "key-round": KeyRound,
  "shield": Shield,
  "crown": Crown,
  "award": Award,
  "stamp": Stamp,
  "signature": Signature,
  "banknote": Banknote,
  "coins": Coins,
  "credit-card": CreditCard,
  "receipt": Receipt,
  "piggy-bank": PiggyBank,
  "wallet": Wallet,
  "calculator": Calculator,
  "chart-column": ChartColumn,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "lock": Lock,
  "vault": Vault,
  "hand-coins": HandCoins,
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
  "clock": Clock,
  "hourglass": Hourglass,
  "bell": Bell,
  "megaphone": Megaphone,
  "mic": Mic,
  "messages-square": MessagesSquare,
  "handshake": Handshake,
  "check-check": CheckCheck,
  "circle-x": CircleX,
  "repeat": Repeat,
  "video": Video,
  "presentation": Presentation,
  "mail": Mail,
  "inbox": Inbox,
  "send": Send,
  "phone": Phone,
  "smartphone": Smartphone,
  "radio": Radio,
  "newspaper": Newspaper,
  "monitor": Monitor,
  "laptop": Laptop,
  "globe": Globe,
  "rss": Rss,
  "at-sign": AtSign,
  "wrench": Wrench,
  "hammer": Hammer,
  "cog": Cog,
  "briefcase": Briefcase,
  "drill": Drill,
  "brick-wall": BrickWall,
  "construction": Construction,
  "hard-hat": HardHat,
  "fire-extinguisher": FireExtinguisher,
  "plug": Plug,
  "paint-roller": PaintRoller,
  "package": Package,
  "brush": Brush,
  "truck": Truck,
  "bus": Bus,
  "car": Car,
  "car-front": CarFront,
  "caravan": Caravan,
  "fuel": Fuel,
  "map": Map,
  "map-pin": MapPin,
  "compass": Compass,
  "traffic-cone": TrafficCone,
  "siren": Siren,
  "route": Route,
  "navigation": Navigation,
  "circle-parking": CircleParking,
  "milestone": Milestone,
  "forklift": Forklift,
  "book": Book,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  "school": School,
  "microscope": Microscope,
  "telescope": Telescope,
  "flask-conical": FlaskConical,
  "lightbulb": Lightbulb,
  "brain": Brain,
  "pencil": Pencil,
  "medal": Medal,
  "stethoscope": Stethoscope,
  "cross": Cross,
  "pill": Pill,
  "ambulance": Ambulance,
  "heart-handshake": HeartHandshake,
  "heart": Heart,
  "life-buoy": LifeBuoy,
  "hand-heart": HandHeart,
  "activity": Activity,
  "users": Users,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "hand": Hand,
  "house": House,
  "building": Building,
  "building-2": Building2,
  "earth": Earth,
  "tent-tree": TentTree,
  "group": Group,
  "utensils": Utensils,
  "coffee": Coffee,
  "croissant": Croissant,
  "soup": Soup,
  "chef-hat": ChefHat,
  "shopping-cart": ShoppingCart,
  "cake": Cake,
  "cup-soda": CupSoda,
  "wheat": Wheat,
  "party-popper": PartyPopper,
  "drama": Drama,
  "music": Music,
  "palette": Palette,
  "film": Film,
  "camera": Camera,
  "trophy": Trophy,
  "ticket": Ticket,
  "sparkles": Sparkles,
  "volleyball": Volleyball,
  "dumbbell": Dumbbell,
  "bike": Bike,
  "footprints": Footprints,
  "fish": Fish,
  "tent": Tent,
  "dices": Dices,
  "target": Target,
  "waves-ladder": WavesLadder,
  "leaf": Leaf,
  "trees": Trees,
  "snowflake": Snowflake,
  "sun": Sun,
  "sprout": Sprout,
  "paw-print": PawPrint,
  "cloud-sun": CloudSun,
  "flower": Flower,
  "mountain-snow": MountainSnow,
  "star": Star,
  "square": Square,
  "triangle": Triangle,
  "flag": Flag,
  "hash": Hash,
  "infinity": Infinity,
  "zap": Zap,
  "bookmark-check": BookmarkCheck,
  "shapes": Shapes,
  "circle-dot": CircleDot,
};

export const LUCIDE_PREFIX = "lucide:";
export const isIconMark = (v?: string | null) => !!v && v.startsWith(LUCIDE_PREFIX);
export const iconName = (v: string) => v.slice(LUCIDE_PREFIX.length);
