headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/admin/Desktop/Kolis/admin-web/admin-web/.next"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/admin/Desktop/Kolis/admin-web"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]